version: '3.8'

services:
  api:
    build: ./build
    image: gallery_api
    container_name: api
    expose:
      - 8000
    networks: 
      - hell
    volumes:
      - ./api:/usr/src/app
    command: gunicorn -b 0.0.0.0:8000 app:app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - mysql-db

  celery:
    image: gallery_api
    container_name: api_celery
    networks: 
      - hell
    volumes:
      - ./api:/usr/src/app
      - ./api/logs:/usr/src/app/logs
    command: celery --app=tasks worker --loglevel=info  --logfile=logs/celery.log
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
      - mysql-db

  redis:
    image: redis:6-alpine
    container_name: api_redis
    networks: 
      - hell

  mysql-db:
    image: mysql:5.6
    container_name: api_db
    ports:
      - 3306:3306
    networks: 
      - hell
    expose:
      - 3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./api/db:/var/lib/mysql
    environment:
      MYSQL_USER: asdfasdf
      MYSQL_PASSWORD: asdfasdf
      MYSQL_DATABASE: gallerydb
      MYSQL_ROOT_PASSWORD: asdfasdfasdf

  monitor:
    image: gallery_api
    container_name: api_monitor
    volumes:
      - ./api:/usr/src/app
    networks: 
      - hell
    expose:
      - 5555
    command: celery -A tasks --broker=redis://redis:6379/0 flower --port=5555
    depends_on:
      - api
      - redis
      - mysql-db
  ui:
    image: gallery-ui
    container_name: ui_dev
    build: ./ui
    networks: 
      - hell
    volumes:
      - './ui:/app'
      - './ui/node_modules:/app/node_modules'
    expose:
      - 3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  nginx:
    image: nginx
    container_name: nginx
    networks: 
      - hell
    volumes:
      - ./api/img:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 3000:3000
      - 5555:5555
      - 8000:8000
    depends_on:
      - ui
      - api
      - monitor


networks: 
  hell: